info:
  name: products
  type: http
  seq: 1

http:
  method: GET
  url: "{{versioned_url}}/products"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
