info:
  name: product flash sale info
  type: http
  seq: 3

http:
  method: GET
  url: "{{versioned_url}}/products"
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
