version: '3.8'

services:
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s

  api:
    image: flashdrop/api:latest
    environment:
      NODE_ENV: production
      PORT: 4000
      HOST: 0.0.0.0
      DATABASE_URL: mongodb://mongodb:27017/flashdrop
      REDIS_URL: redis://redis:6379
      WORKERS: 1
    ports:
      - target: 4000
        published: 4000
        protocol: tcp
        mode: ingress   # default, enables Swarm load-balancing
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
        delay: 5s
    healthcheck:
      test: ["CMD-SHELL", "node -e 'require(\"http\").get(\"http://127.0.0.1:4000/api/v1/health\",()=>{})' || exit 1"]
      interval: 10s
      retries: 5
      start_period: 20s   # give server time to fully initialize

  prometheus:
    image: prom/prometheus:v2.52.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus

  grafana:
    image: grafana/grafana:11.2.0
    ports:
      - "4001:4001"
    environment:
      GF_SERVER_HTTP_PORT: 4001
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  mongo_data:
  prometheus_data:
  grafana_data:
