info:
  name: products/:sku
  type: http
  seq: 2

http:
  method: GET
  url: "{{versioned_url}}/products/:sku"
  params:
    - name: sku
      value: IPHONE-17-PRO-MAX-256-BLK
      type: path
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
